config/routes.rb
Tasks::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :lists do
    resources :tasks
  end

  devise_for :users

  root to: "lists#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    #For Lists
    can :create, List
    can :update, List do |list|
      list.try(:user) == user
    end
  
    can :destroy, List do |list|
      list.try(:user) == user
    end

    #For Tasks
    can :create, Task
    can :update, Task do |task|
      task.try(:list).try(:user) == user
    end 

    can :destroy, Task do |task|
      task.try(:list).try(:user) == user
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  validates_presence_of :name, :user_id
  belongs_to :user
  attr_accessible :name, :user_id
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :date, :latitude, :list_id, :longitude, :remind_by_date, :remind_by_location, :repeat, :text, :address
  validates_presence_of :text, :list_id

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  attr_accessible :email, :password, :password_confirmation, :remember_me,
          :provider, :uid, :full_name

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(full_name: auth.extra.raw_info.name,
                          provider: auth.provider,
                          uid: auth.uid,
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied!"
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  respond_to :js, except: [:index]

  def index
    @list = List.new
    @lists = current_user.lists
  end

  def create
    @list = current_user.lists.build(params[:list])
    @list.save
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
  end

  def destroy
    @list = List.destroy(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  respond_to :js

  def new
    @task = Task.new
    @list = List.find(params[:list_id])
    respond_with :js
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(params[:task])
    @task.completed = false
    @task.date = nil unless @task.remind_by_date
    @task.address = "" unless @task.remind_by_location
    @task.save
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    respond_with :js
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    params[:task][:date] = nil if params[:task][:remind_by_date] == '0'
    params[:task][:address] = "" if params[:task][:remind_by_location] == '0'
    
    @task.update_attributes(params[:task])
  end

  def destroy
    @task = Task.destroy(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def fb_sso_proxy
    session[:user_return_to] = params[:return_to] if params[:return_to]
    redirect_to user_omniauth_authorize_path(:facebook)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
      when :alert
        "alert-error"
      when :notice
        "alert-success"
      else
        ""
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Tasks
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .navbar.navbar-static-top.navbar-inverse
    .navbar-inner
      %a.brand{href: "#{root_path}"} Tasks
      %ul.nav
        %li.active
          %a{href: "#"} Home
      %ul{class: "nav pull-right"}
        -if user_signed_in?
          %li
            .btn-group
              %a.btn.btn-info.dropdown-toggle{"data-toggle" => "dropdown", href: "#{current_user.full_name}"}
                =current_user.full_name
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to "Log Out", destroy_user_session_path, method: :delete
  
  .container
    - flash.each do |type, message|
      %div{class: "alert #{flash_class type}"}
        %button.close{"data-dismiss" => "alert"} x
        = message

  - unless user_signed_in?
    = render 'login'
  - else
    = yield

app/views/lists/_list.html.haml
%tr.info{id: "list_#{list.id}"}
  %td{style: "width: 20px"}
    = link_to(list_path(list), method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: 'btn btn-mini') do
      %i.icon-remove
  %td
    = link_to(list.name, list_path(list), remote: true, class: 'list')

app/views/lists/_login.html.haml
#log-carousel.carousel.slid
  %a{href: "#{user_omniauth_authorize_path(:facebook)}"}
    .btn-face
  / Carousel items
  .carousel-inner.thumbnail
    .active.item
      %img{:src => "assets/task2.jpg?_=#{Random.rand()}", style: "height: 558px; width: 940px"}
      .carousel-caption
        %h4 Second Thumbnail label
        %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
    .item
      %img{:src => "assets/task1.jpg?_=#{Random.rand()}", style: "height: 558px; width: 940px"}
      .carousel-caption
        %h4 Second Thumbnail label
        %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
  / Carousel nav
  %a.carousel-control.left{"data-slide" => "prev", :href => "#log-carousel"} &lsaquo;
  %a.carousel-control.right{"data-slide" => "next", :href => "#log-carousel"} &rsaquo;

app/views/lists/_welcome.html.haml
%h4.muted{style: "margin: 50px auto; text-align: center; height: 100px;"}
  %p
    Create a new List
    %br or
    Select a List to view its tasks

app/views/lists/create.js.haml
$('table#lists tbody').append("#{ j render @list }");
$('#list_name').val('');

app/views/lists/destroy.js.haml
$("#list_#{@list.id}").remove();
$('#tasks').html("#{ j render 'welcome' }");

app/views/lists/index.html.haml
.container-fluid#content
  .row-fluid
    .span4.well.well-small
      %h3
        Lists

      = simple_form_for(@list, remote: true, html: {class: 'form-search'}) do |f|
        = f.input :name
        = f.button :submit, "Create List"

      %table#lists.table.table-hover
        %tbody
          = render @lists

    .span8.well.well-small#tasks
      = render 'welcome'

#task_dialog.hide.fade.modal

app/views/lists/show.js.haml
$('#tasks').html("#{ j render 'tasks/tasks_list' }");
$('#lists tr').removeClass('active');
$("#list_#{@list.id}").addClass('active');

app/views/tasks/_form.html.haml
= simple_form_for([@list, @task], remote: true, html: {style: 'margin:0'}) do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
    %h3 
      = params['action'] == 'new' ? 'New Task' : 'Edit Task'
  .modal-body
    = f.input :text
    .row-fluid
      #accordion2.accordion
        .span4
          .accordion-group
            .accordion-heading
              %label.checkbox
                =f.input :remind_by_date, label: false, inline_label: 'Remind by Date', input_html: {data: {target: "#collapse-by-date"}}
              #collapse-by-date{class: "accordion-body collapse #{'in' if @task.remind_by_date}"}
                .accordion-inner
                  =f.input :date, as: :string, input_html: {id: 'datetimepicker', value: "#{@task.date.strftime("%Y-%m-%d %H:%M") unless @task.date.nil?}", style: "width: 120px"}
        .span8
          .accordion-group
            .accordion-heading
              %label.checkbox
                = f.input :remind_by_location, label: false, inline_label: 'Remind by Location', input_html: {style: "width: 96%", data: {target: "#collapse-by-location"}}
            #collapse-by-location{class: "accordion-body collapse #{'in' if @task.remind_by_location}"}
              .accordion-inner
                = f.input :address
                %a.btn{href: "http://maps.google.com/maps/api/staticmap?size=640x640&maptype=hybrid&sensor=true&zoom=16&markers=#{@task.latitude}%2C#{@task.longitude}", target: "_blank"}
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=450x230&maptype=hybrid&sensor=true&zoom=16&markers=#{@task.latitude}%2C#{@task.longitude}"
  
  .modal-footer
    = f.button :submit, class: 'btn-info'

app/views/tasks/_task.html.haml
.row-fluid
  .span10
    %p.muted.pull-right.task_meta
      %small
        = task.address
        = task.date.strftime("| %d/%b/%Y %I:%M %P") unless task.date.nil?
    = simple_form_for([@list, task], remote: true, html: {style: 'margin: 0'}) do |f|
      = f.input :completed, label: false, inline_label: task.text, input_html: {class: "task_check", data: {id: "#{task.id}"}},  wrapper_html: { class: "#{'completed-task' if task.completed}" } 
  
  .span1
    .task_actions.btn-group
      %button{class: "btn btn-info btn-small edit_task_button", "data-toggle" => "modal", "data-action" => "#{edit_list_task_path(@list, task)}"}
        %i.icon-pencil.icon-white

      = link_to(list_task_path(@list, task), method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: 'btn btn-small') do
        %i.icon-remove

app/views/tasks/_tasks_list.html.haml
#list_title.page-header
  %a.btn.btn-success.pull-right#new_task_button{'data-action' => "#{new_list_task_path @list}", 'data-toggle' => "modal"}
    New Task
  %h2
    =@list.name

#tasks_list
  %ul#tasks.unstyled
    -@tasks.each do |task|
      %li.task{id: "task_#{task.id}"}
        =render task

app/views/tasks/create.js.haml
$('#tasks_list ul').append("<li class=\"task\" id=\"task_#{@task.id}\">#{ j render @task}</li>");
$('#task_dialog').modal('hide');

app/views/tasks/destroy.js.haml
$("#task_#{@task.id}").remove();

app/views/tasks/edit.html.haml
= render 'form'

app/views/tasks/new.html.haml
= render 'form'

app/views/tasks/update.js.haml
$("#task_#{@task.id}").html("#{ j render @task}");
$('#task_dialog').modal('hide');
$("#task_#{@task.id} label.checkbox").addClass("#{'completed-task' if @task.completed}");